# Generated by Django 6.0.6 on 2026-09-22 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_operator_saas_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Razão Social ou Nome Fantasia do Operador Logístico.', max_length=255)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da operadora para emissão de Notas e cobranças.', max_length=14, null=True)),
                ('phone', models.CharField(blank=True, help_text='Telefone ou WhatsApp de contato.', max_length=50, null=True)),
                ('city', models.CharField(blank=True, help_text='Cidade sede do operador.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='UF / Estado.', max_length=10, null=True)),
                ('billingPlanType', models.CharField(choices=[('PERCENT_PER_DELIVERY', 'Percentual por Entrega'), ('PERCENT_REVENUE', 'Percentual sobre Faturamento'), ('FIXED_MONTHLY', 'Fixo Mensal'), ('FIXED_WEEKLY', 'Fixo Semanal'), ('FIXED_PER_DELIVERY', 'Fixo por Corrida')], db_column='billingPlanType', default='PERCENT_PER_DELIVERY', help_text='Modalidade de cobrança do operador.', max_length=50)),
                ('billingRateValue', models.DecimalField(db_column='billingRateValue', decimal_places=2, default=0.0, help_text='Valor fixo (R$) ou percentual (%) cobrado do operador.', max_digits=10)),
                ('billingCycle', models.CharField(choices=[('MENSAL', 'Mensal'), ('QUINZENAL', 'Quinzenal'), ('SEMANAL', 'Semanal')], db_column='billingCycle', default='MENSAL', help_text='Ciclo de cobrança/faturamento.', max_length=30)),
                ('dueDay', models.IntegerField(db_column='dueDay', default=10, help_text='Dia de vencimento da fatura (1 a 31).')),
                ('trialDays', models.IntegerField(db_column='trialDays', default=14, help_text='Dias de carência/degustação gratuita.')),
                ('gracePeriodDays', models.IntegerField(db_column='gracePeriodDays', default=5, help_text='Dias de tolerância antes do bloqueio por inadimplência.')),
                ('notes', models.TextField(blank=True, help_text='Termos contratuais e observações financeiras.', null=True)),
                ('platformCostPerDeliveryCents', models.IntegerField(db_column='platformCostPerDeliveryCents', default=40, help_text='Taxa cobrada pela plataforma SaaS por entrega concluída (em centavos, ex: 40 = R$ 0,40).')),
                ('platformMinMonthlyFloorCents', models.IntegerField(db_column='platformMinMonthlyFloorCents', default=29900, help_text='Piso mínimo de faturamento mensal garantido da plataforma SaaS (em centavos, ex: 29900 = R$ 299,00).')),
                ('platformVolumeTiers', models.JSONField(blank=True, db_column='platformVolumeTiers', default=list, help_text='Faixas de volume e tarifas escalonadas da plataforma SaaS em formato JSON.')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled')], default='TRIAL', help_text='Status atual da assinatura/contrato na plataforma.', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Operador Logístico',
                'verbose_name_plural': 'Operadores Logísticos',
                'db_table': 'Operator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorAuditLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Tipo da ação (ex: STATUS_CHANGE).', max_length=100)),
                ('previousStatus', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled')], db_column='previousStatus', max_length=20, null=True)),
                ('newStatus', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled')], db_column='newStatus', max_length=20, null=True)),
                ('reason', models.TextField(help_text='Justificativa obrigatória para a mudança.')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'OperatorAuditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('supabase_uid', models.UUIDField(blank=True, help_text='Identificador legado Supabase Auth (opcional).', null=True)),
                ('name', models.CharField(help_text='Nome completo do administrador.', max_length=255)),
                ('email', models.CharField(help_text='E-mail de login corporativo.', max_length=255, unique=True)),
                ('passwordHash', models.CharField(blank=True, db_column='passwordHash', help_text='Hash PBKDF2 da senha de acesso.', max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'verbose_name': 'Administrador da Plataforma',
                'verbose_name_plural': 'Administradores da Plataforma',
                'db_table': 'PlatformAdmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityDenylist',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('targetId', models.UUIDField(db_column='targetId', help_text='ID do artefato bloqueado (ex: ID do Device Token).')),
                ('targetType', models.CharField(db_column='targetType', help_text='Tipo do bloqueio (ex: DEVICE_TOKEN, IP).', max_length=50)),
                ('reason', models.TextField(help_text='Motivo do bloqueio (ex: Suspeita de fraude, Token vazado).')),
                ('blockedAt', models.DateTimeField(auto_now_add=True, db_column='blockedAt')),
                ('expiresAt', models.DateTimeField(blank=True, db_column='expiresAt', help_text='Data de expiração do bloqueio, se aplicável.', null=True)),
            ],
            options={
                'verbose_name': 'Bloqueio de Segurana',
                'verbose_name_plural': 'Bloqueios de Segurana',
                'db_table': 'SecurityDenylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('supabase_uid', models.UUIDField(blank=True, help_text='Vínculo legado Supabase Auth (opcional).', null=True)),
                ('name', models.CharField(help_text='Nome do funcionário.', max_length=255)),
                ('email', models.CharField(help_text='E-mail de acesso.', max_length=255)),
                ('passwordHash', models.CharField(blank=True, db_column='passwordHash', help_text='Hash PBKDF2 da senha de acesso.', max_length=255, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR_ROLE', 'Operator'), ('VIEWER', 'Viewer')], default='OPERATOR_ROLE', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Define se o acesso está ativo ou revogado.')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'db_table': 'StaffMember',
                'managed': False,
            },
        ),
    ]
