events {
    worker_connections 1024;
}

http {
    upstream django_backend {
        server django:8000;
    }

    upstream fast_lane {
        server fastapi:8001;
    }

    server {
        listen 80;

        # Rota de Telemetria de Altíssima Performance vai para o FastAPI
        location /telemetry {
            proxy_pass http://fast_lane;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Restante das rotas vai para o Django (Slow Lane)
        location / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Arquivos estáticos do Django (Admin)
        location /static/ {
            alias /app/static/;
        }
    }
}
