# Generated by Django 6.0.6 on 2026-06-21 04:39

from django.db import migrations
from django.db import connection


def run_sql_when_postgres(apps, schema_editor):
    if connection.vendor == "postgresql":
        schema_editor.execute("""
            CREATE OR REPLACE FUNCTION process_wallet_transaction()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Update Source Driver Wallet (Debit)
                IF NEW.source_driver_wallet_id IS NOT NULL THEN
                    UPDATE "Wallet" 
                    SET "balanceCents" = "balanceCents" - NEW."amountCents", "updatedAt" = NOW()
                    WHERE id = NEW.source_driver_wallet_id;
                END IF;

                -- Update Destination Driver Wallet (Credit)
                IF NEW.destination_driver_wallet_id IS NOT NULL THEN
                    UPDATE "Wallet" 
                    SET "balanceCents" = "balanceCents" + NEW."amountCents", "updatedAt" = NOW()
                    WHERE id = NEW.destination_driver_wallet_id;
                END IF;

                -- Update Source Operator Wallet (Debit)
                IF NEW.source_operator_wallet_id IS NOT NULL THEN
                    UPDATE "OperatorInternalWallet" 
                    SET "balanceCents" = "balanceCents" - NEW."amountCents", "updatedAt" = NOW()
                    WHERE id = NEW.source_operator_wallet_id;
                END IF;

                -- Update Destination Operator Wallet (Credit)
                IF NEW.destination_operator_wallet_id IS NOT NULL THEN
                    UPDATE "OperatorInternalWallet" 
                    SET "balanceCents" = "balanceCents" + NEW."amountCents", "updatedAt" = NOW()
                    WHERE id = NEW.destination_operator_wallet_id;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trigger_wallet_transaction ON "WalletTransaction";
            
            CREATE TRIGGER trigger_wallet_transaction
            AFTER INSERT ON "WalletTransaction"
            FOR EACH ROW
            EXECUTE FUNCTION process_wallet_transaction();
        """)


def reverse_sql_when_postgres(apps, schema_editor):
    if connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER IF EXISTS trigger_wallet_transaction ON "WalletTransaction";
            DROP FUNCTION IF EXISTS process_wallet_transaction();
        """)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            code=run_sql_when_postgres,
            reverse_code=reverse_sql_when_postgres
        )
    ]
