# Generated by Django 6.0.6 on 2026-09-22 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEventAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('provider', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=20)),
                ('eventType', models.CharField(db_column='eventType', max_length=100)),
                ('externalEventId', models.CharField(blank=True, db_column='externalEventId', max_length=255, null=True)),
                ('externalOrderId', models.CharField(blank=True, db_column='externalOrderId', max_length=255, null=True)),
                ('merchantReference', models.CharField(blank=True, db_column='merchantReference', max_length=100, null=True)),
                ('deliveryStatus', models.CharField(db_column='deliveryStatus', max_length=30)),
                ('httpStatusCode', models.IntegerField(blank=True, db_column='httpStatusCode', null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('responsePayload', models.JSONField(blank=True, db_column='responsePayload', default=dict)),
                ('failReason', models.TextField(blank=True, db_column='failReason', null=True)),
                ('processedAt', models.DateTimeField(blank=True, db_column='processedAt', null=True)),
            ],
            options={
                'verbose_name': 'Auditoria de Evento de Integração',
                'verbose_name_plural': 'Auditorias de Eventos de Integração',
                'db_table': 'IntegrationEventAudit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('aggregateType', models.CharField(db_column='aggregateType', help_text='Entidade alvo (Ex: ORDER).', max_length=100)),
                ('aggregateId', models.UUIDField(db_column='aggregateId', help_text='ID do registro afetado.')),
                ('sequenceNumber', models.BigIntegerField(db_column='sequenceNumber', editable=False, help_text='Garante FIFO absoluto. Auto-gerado via BIGSERIAL no Postgres.', unique=True)),
                ('eventType', models.CharField(db_column='eventType', help_text='Ação ocorrida (Ex: ORDER_ACCEPTED).', max_length=100)),
                ('payload', models.JSONField(help_text='Snapshot do payload JSON a ser transmitido ao webhook.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('attempts', models.IntegerField(default=0, help_text='Retries com backoff exponencial.')),
                ('lastAttemptAt', models.DateTimeField(blank=True, db_column='lastAttemptAt', null=True)),
                ('failReason', models.TextField(blank=True, db_column='failReason', help_text='Armazena os status codes ou timeouts (504, 500, etc).', null=True)),
            ],
            options={
                'verbose_name': 'Fila de Integração (Outbox)',
                'verbose_name_plural': 'Filas de Integração (Outbox)',
                'db_table': 'IntegrationOutbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('provider', models.CharField(help_text='Provedor (Ex: HUBSTER, IFOOD).', max_length=50)),
                ('clientId', models.CharField(blank=True, db_column='clientId', max_length=255, null=True)),
                ('clientSecret', models.TextField(blank=True, db_column='clientSecret', help_text='Senha de integração.', null=True)),
                ('merchantId', models.CharField(blank=True, db_column='merchantId', max_length=100, null=True)),
                ('authMode', models.CharField(db_column='authMode', default='WEBHOOK', max_length=30)),
                ('baseUrl', models.TextField(blank=True, db_column='baseUrl', null=True)),
                ('webhookUrl', models.TextField(blank=True, db_column='webhookUrl', null=True)),
                ('apiKey', models.TextField(blank=True, db_column='apiKey', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integração da Loja',
                'verbose_name_plural': 'Integrações das Lojas',
                'db_table': 'StoreIntegration',
                'managed': False,
            },
        ),
    ]
