# Generated by Django 6.0.6 on 2026-09-22 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_wallet_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compensationMode', models.CharField(choices=[('PRODUCAO', 'Producao'), ('GARANTIDA', 'Garantida'), ('GARANTIDA_HORAS', 'Garantida Horas')], db_column='compensationMode', default='GARANTIDA', max_length=20)),
                ('rideFeePerDeliveryCents', models.IntegerField(db_column='rideFeePerDeliveryCents', help_text='Taxa fixa de corrida repassada.')),
                ('minimumRidesFeeFloorCents', models.IntegerField(db_column='minimumRidesFeeFloorCents')),
                ('minimumFloorBps', models.IntegerField(db_column='minimumFloorBps')),
                ('adminTaxThresholdCents', models.IntegerField(db_column='adminTaxThresholdCents')),
                ('adminTaxFixedAmountCents', models.IntegerField(db_column='adminTaxFixedAmountCents')),
                ('adminTaxBps', models.IntegerField(db_column='adminTaxBps')),
                ('supervisionFeePerWeekCents', models.IntegerField(db_column='supervisionFeePerWeekCents', default=0)),
                ('dailyRateWeekdayCents', models.IntegerField(db_column='dailyRateWeekdayCents', default=0)),
                ('dailyRateSaturdayCents', models.IntegerField(db_column='dailyRateSaturdayCents', default=0)),
                ('dailyRateSundayCents', models.IntegerField(db_column='dailyRateSundayCents', default=0)),
                ('dailyRateHolidayCents', models.IntegerField(db_column='dailyRateHolidayCents', default=0)),
                ('kmExcedenteValorCents', models.IntegerField(db_column='kmExcedenteValorCents', default=0)),
                ('allowAutomaticGrouping', models.BooleanField(db_column='allowAutomaticGrouping', default=True)),
                ('cloudOverflowAllowed', models.BooleanField(db_column='cloudOverflowAllowed', default=False)),
                ('maxStopsPerManifest', models.IntegerField(db_column='maxStopsPerManifest', default=3)),
                ('maxDetourPercent', models.IntegerField(db_column='maxDetourPercent', default=20)),
                ('cutoffHour', models.IntegerField(db_column='cutoffHour', default=2, help_text="Hora oficial de fechamento do 'business date'.")),
                ('cutoffMinute', models.IntegerField(db_column='cutoffMinute', default=0)),
                ('returnFeeBps', models.IntegerField(db_column='returnFeeBps', default=5000)),
                ('overridePayoutPolicy', models.BooleanField(db_column='overridePayoutPolicy', default=False, help_text='Se True, aplica as regras customizadas de saque da loja ao invés da política global do operador.')),
                ('customPayoutMode', models.CharField(blank=True, db_column='customPayoutMode', max_length=30, null=True)),
                ('customAutoThresholdCents', models.BigIntegerField(blank=True, db_column='customAutoThresholdCents', null=True)),
                ('customFeeMode', models.CharField(blank=True, db_column='customFeeMode', max_length=30, null=True)),
                ('customFeeCents', models.BigIntegerField(blank=True, db_column='customFeeCents', null=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyCreditCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('date', models.DateField(help_text='O Business Date computado para a apuração.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('productionValueCents', models.BigIntegerField(db_column='productionValueCents', default=0)),
                ('extrasCents', models.BigIntegerField(db_column='extrasCents', default=0)),
                ('dailyRateOrGuaranteedCents', models.BigIntegerField(db_column='dailyRateOrGuaranteedCents', default=0)),
                ('advancesCents', models.BigIntegerField(db_column='advancesCents', default=0)),
                ('netAmountCents', models.BigIntegerField(db_column='netAmountCents', default=0)),
                ('failReason', models.TextField(blank=True, db_column='failReason', null=True)),
            ],
            options={
                'db_table': 'DailyCreditCalculation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('type', models.CharField(max_length=20)),
                ('amountCents', models.BigIntegerField(db_column='amountCents')),
                ('description', models.TextField()),
                ('status', models.CharField(default='SUBMITTED', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'DriverExpense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverExpenseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('fileUrl', models.TextField(db_column='fileUrl')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'DriverExpenseReceipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaHoras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hoursMin', models.DecimalField(db_column='hoursMin', decimal_places=2, max_digits=4)),
                ('hoursMax', models.DecimalField(db_column='hoursMax', decimal_places=2, max_digits=4)),
                ('priceCents', models.IntegerField(db_column='priceCents')),
            ],
            options={
                'db_table': 'FaixaHoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KmFaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kmStart', models.IntegerField(db_column='kmStart')),
                ('kmEnd', models.IntegerField(db_column='kmEnd')),
                ('priceCents', models.IntegerField(db_column='priceCents')),
            ],
            options={
                'db_table': 'KmFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('amountCents', models.BigIntegerField(db_column='amountCents')),
                ('description', models.TextField()),
                ('visibleToStore', models.BooleanField(db_column='visibleToStore', default=True)),
                ('taxCategory', models.CharField(choices=[('TAXABLE_INCOME', 'Taxable Income'), ('NON_TAXABLE_REIMBURSEMENT', 'Non Taxable Reimbursement'), ('DEDUCTION', 'Deduction')], db_column='taxCategory', max_length=50)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=30)),
                ('rejectReason', models.TextField(blank=True, db_column='rejectReason', null=True)),
            ],
            options={
                'db_table': 'ManualEntry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorInternalWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balanceCents', models.BigIntegerField(db_column='balanceCents', default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'OperatorInternalWallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutPolicyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('mode', models.CharField(choices=[('HYBRID_THRESHOLD', 'Híbrido (Alçada)'), ('MANUAL_ALL', 'Aprovação Manual para Todos')], db_column='mode', default='HYBRID_THRESHOLD', max_length=30)),
                ('autoThresholdCents', models.BigIntegerField(db_column='autoThresholdCents', default=15000, help_text='Valor máximo em centavos para liberação automática de PIX (ex: 15000 = R$ 150,00).')),
                ('dailyLimitPerDriverCents', models.BigIntegerField(db_column='dailyLimitPerDriverCents', default=50000, help_text='Teto diário acumulado de saque por motoboy nas últimas 24h.')),
                ('minWithdrawalCents', models.BigIntegerField(db_column='minWithdrawalCents', default=1000, help_text='Valor mínimo por solicitação de saque.')),
                ('payoutFeeMode', models.CharField(choices=[('ABSORBED_BY_PLATFORM', 'Absorvida pela Plataforma'), ('CHARGED_TO_DRIVER', 'Cobrada do Entregador')], db_column='payoutFeeMode', default='ABSORBED_BY_PLATFORM', max_length=30)),
                ('payoutFeeCents', models.BigIntegerField(db_column='payoutFeeCents', default=0, help_text='Taxa fixa retida do entregador quando payoutFeeMode = CHARGED_TO_DRIVER.')),
                ('notifyPushEnabled', models.BooleanField(db_column='notifyPushEnabled', default=True, help_text='Disparar notificação Push via FCM no NevesGo ao concluir PIX.')),
                ('notifyWhatsappEnabled', models.BooleanField(db_column='notifyWhatsappEnabled', default=True, help_text='Enviar mensagem e comprovante PIX via Z-API WhatsApp.')),
            ],
            options={
                'verbose_name': 'Configuração de Política de Saque',
                'verbose_name_plural': 'Configurações de Políticas de Saque',
                'db_table': 'PayoutPolicyConfig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balanceCents', models.BigIntegerField(db_column='balanceCents', default=0, help_text='Saldo computado.')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Wallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('amountCents', models.BigIntegerField(db_column='amountCents')),
                ('category', models.CharField(choices=[('DAILY_SETTLEMENT', 'Daily Settlement'), ('ADVANCE', 'Advance'), ('PAYOUT', 'Payout'), ('ADJUSTMENT', 'Adjustment'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('RETURN_RIDE', 'Return Ride'), ('REFUND', 'Refund')], max_length=50)),
                ('taxCategory', models.CharField(choices=[('TAXABLE_INCOME', 'Taxable Income'), ('NON_TAXABLE_REIMBURSEMENT', 'Non Taxable Reimbursement'), ('DEDUCTION', 'Deduction')], db_column='taxCategory', max_length=50)),
            ],
            options={
                'db_table': 'WalletTransaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyInvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('businessDate', models.DateField(blank=True, db_column='businessDate', null=True)),
                ('description', models.TextField()),
                ('amountCents', models.BigIntegerField(db_column='amountCents')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPUTED', 'Disputed'), ('WAIVED', 'Waived')], default='ACTIVE', max_length=20)),
                ('disputeReason', models.TextField(blank=True, db_column='disputeReason', null=True)),
            ],
            options={
                'db_table': 'WeeklyInvoiceLineItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyStoreInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('startDate', models.DateField(db_column='startDate')),
                ('endDate', models.DateField(db_column='endDate')),
                ('totalNetProducaoCents', models.BigIntegerField(db_column='totalNetProducaoCents', default=0)),
                ('totalNetGarantidaCents', models.BigIntegerField(db_column='totalNetGarantidaCents', default=0)),
                ('administrativeFeeCents', models.BigIntegerField(db_column='administrativeFeeCents', default=0)),
                ('supervisionFeeCents', models.BigIntegerField(db_column='supervisionFeeCents', default=0)),
                ('pendingDebitCarriedCents', models.BigIntegerField(db_column='pendingDebitCarriedCents', default=0)),
                ('totalCents', models.BigIntegerField(db_column='totalCents', default=0, help_text='Total geral da fatura que será enviado ao Gateway.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPUTED', 'Disputed'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('paymentGatewayId', models.CharField(blank=True, db_column='paymentGatewayId', help_text='ID do Gateway de Pagamento (Asaas/Stripe).', max_length=255, null=True)),
                ('pixCopyPaste', models.TextField(blank=True, db_column='pixCopyPaste', null=True)),
                ('barcode', models.TextField(blank=True, null=True)),
                ('pdfUrl', models.CharField(blank=True, db_column='pdfUrl', max_length=255, null=True)),
            ],
            options={
                'db_table': 'WeeklyStoreInvoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('amountCents', models.BigIntegerField(db_column='amountCents')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('pixKey', models.CharField(db_column='pixKey', max_length=255)),
                ('pixKeyType', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('EVP', 'Chave Aleatória (EVP)')], db_column='pixKeyType', default='CPF', max_length=20)),
                ('approvalMode', models.CharField(choices=[('AUTO_INSTANT', 'Automático Imediato'), ('MANUAL_PENDING', 'Aprovação Manual')], db_column='approvalMode', default='AUTO_INSTANT', max_length=30)),
                ('feeAmountCents', models.BigIntegerField(db_column='feeAmountCents', default=0)),
                ('netAmountCents', models.BigIntegerField(db_column='netAmountCents', default=0)),
                ('approvedAt', models.DateTimeField(blank=True, db_column='approvedAt', null=True)),
                ('rejectionReason', models.TextField(blank=True, db_column='rejectionReason', null=True)),
                ('baasProvider', models.CharField(db_column='baasProvider', default='EFI_PAY', max_length=50)),
                ('baasTransactionId', models.CharField(blank=True, db_column='baasTransactionId', max_length=255, null=True)),
                ('baasRawResponse', models.JSONField(blank=True, db_column='baasRawResponse', default=dict)),
                ('failureReason', models.TextField(blank=True, db_column='failureReason', null=True)),
                ('processedAt', models.DateTimeField(blank=True, db_column='processedAt', null=True)),
            ],
            options={
                'verbose_name': 'Pedido de Saque',
                'verbose_name_plural': 'Pedidos de Saque',
                'db_table': 'WithdrawalRequest',
                'managed': False,
            },
        ),
    ]
