# Este arquivo agora atua como um Proxy para a verdadeira fonte da verdade (Shared Schemas).
# Assim, qualquer código legado no Django que importe de logistics.schemas continuará funcionando,
# mas usando as classes puras do Pydantic que compartilhamos com o FastAPI.

from shared_schemas.logistics import (
    StoreSchema,
    DriverSchema,
    StopSchema,
    ManifestSchema,
    OrderSchema,
    StopBatchCompleteItem,
    ShiftCheckInSchema,
    TelemetryPayload,
    DispatchPayload,
    DriverStatusPayload,
    DriverStatusResponse,
    OrderRejectPayload,
    OrderReleasePayload,
    OrderOfferStopSchema,
    OrderOfferDetailResponse,
    DriverCockpitResponse,
    DriverShiftCheckoutPayload,
    DriverIncidentCreatePayload,
    DriverPerformanceResponse,
    DriverCalendarItem,
    DriverShiftReservationPayload,
    DriverDeviceRegisterPayload,
    DriverDeviceAttestationPayload,
    DriverOfflineSyncPayload,
    DriverExpensePayload,
    ComplianceDocumentPayload,
    DriverConsentItem,
    DriverConsentRevokePayload,
    PrivacyDataRequestCreatePayload,
    PrivacyDataRequestResolvePayload,
    PrivacyDataRequestItem,
    ComplianceRetentionPolicyPayload,
    ComplianceRetentionPolicyItem,
    ClientDispatchOrderPayload,
    OrderReassignmentPayload,
    CommunicationThreadCreatePayload,
    CommunicationMessagePayload
)
