# Generated by Django 6.0.6 on 2026-09-22 21:30

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(help_text='Nome da franquia ou cliente embarcador.', max_length=255)),
                ('document', models.CharField(help_text='CNPJ do cliente.', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Parceiro',
                'verbose_name_plural': 'Clientes Parceiros',
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPortalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('supabase_uid', models.UUIDField(help_text='Vínculo com Auth Seguro.', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passwordHash', models.CharField(blank=True, db_column='passwordHash', help_text='Hash PBKDF2 da senha de acesso.', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ClientPortalUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('audienceType', models.CharField(db_column='audienceType', default='DRIVER', max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('effectiveAt', models.DateTimeField(db_column='effectiveAt')),
                ('archivedAt', models.DateTimeField(blank=True, db_column='archivedAt', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ComplianceDocument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('resourceType', models.CharField(db_column='resourceType', max_length=50)),
                ('retentionDays', models.IntegerField(db_column='retentionDays')),
                ('active', models.BooleanField(default=True)),
                ('lastExecutedAt', models.DateTimeField(blank=True, db_column='lastExecutedAt', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ComplianceRetentionPolicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('supabase_uid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('pixKeyType', models.CharField(db_column='pixKeyType', max_length=20)),
                ('pixKey', models.CharField(db_column='pixKey', max_length=255)),
                ('passwordHash', models.CharField(blank=True, db_column='passwordHash', help_text='Hash PBKDF2 da senha de acesso.', max_length=255, null=True)),
                ('online', models.BooleanField(default=False, help_text='Flag indicando se o app do motoboy está rodando no background.')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Último ping válido do device.', null=True, srid=4326)),
                ('heading', models.IntegerField(blank=True, default=0, null=True)),
                ('speedKmh', models.IntegerField(blank=True, db_column='speedKmh', default=0, null=True)),
                ('lastPingAt', models.DateTimeField(blank=True, db_column='lastPingAt', null=True)),
                ('active', models.BooleanField(default=True)),
                ('operational_status', models.CharField(db_column='operational_status', default='OFFLINE', max_length=30)),
                ('maxActiveOrders', models.IntegerField(db_column='maxActiveOrders', default=3)),
                ('onboarding_status', models.CharField(default='INVITED', max_length=50)),
                ('tax_classification', models.CharField(default='PESSOA_FISICA_AUTONOMO', max_length=50)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'Driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverCommunicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('senderType', models.CharField(db_column='senderType', max_length=20)),
                ('senderName', models.CharField(blank=True, db_column='senderName', max_length=255, null=True)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverCommunicationMessage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverCommunicationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('sourceType', models.CharField(db_column='sourceType', default='STORE', max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'DriverCommunicationThread',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverConsentAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceIdentifier', models.CharField(blank=True, db_column='deviceIdentifier', max_length=255, null=True)),
                ('ipAddress', models.CharField(blank=True, db_column='ipAddress', max_length=64, null=True)),
                ('userAgent', models.TextField(blank=True, db_column='userAgent', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acceptedAt', models.DateTimeField(auto_now_add=True, db_column='acceptedAt')),
                ('revokedAt', models.DateTimeField(blank=True, db_column='revokedAt', null=True)),
                ('revokedReason', models.TextField(blank=True, db_column='revokedReason', null=True)),
            ],
            options={
                'db_table': 'DriverConsentAcceptance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceIdentifier', models.CharField(db_column='deviceIdentifier', max_length=255)),
                ('platform', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('trusted', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lastSeenAt', models.DateTimeField(blank=True, db_column='lastSeenAt', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverDevice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDeviceSecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('riskLevel', models.CharField(db_column='riskLevel', max_length=20)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverDeviceSecurityEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('fileUrl', models.TextField(db_column='fileUrl')),
                ('expiresAt', models.DateField(blank=True, db_column='expiresAt', null=True)),
                ('document_type', models.CharField(default='CNH', max_length=50)),
                ('status', models.CharField(default='PENDING_APPROVAL', max_length=50)),
                ('rejectReason', models.TextField(blank=True, db_column='rejectReason', null=True)),
            ],
            options={
                'db_table': 'DriverDocument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDocumentRequirement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tax_class', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'DriverDocumentRequirement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolvedAt', models.DateTimeField(blank=True, db_column='resolvedAt', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverIncident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverIncidentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('fileUrl', models.TextField(db_column='fileUrl')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverIncidentAttachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverOfflineSyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceIdentifier', models.CharField(db_column='deviceIdentifier', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('itemCount', models.IntegerField(db_column='itemCount', default=0)),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('failReason', models.TextField(blank=True, db_column='failReason', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverOfflineSyncBatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverShiftReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(default='REQUESTED', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('decidedAt', models.DateTimeField(blank=True, db_column='decidedAt', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverShiftReservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverShiftSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('checkInAt', models.DateTimeField(db_column='checkInAt')),
                ('checkOutAt', models.DateTimeField(blank=True, db_column='checkOutAt', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverShiftSession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverStatusAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(db_column='previous_status', max_length=30)),
                ('new_status', models.CharField(db_column='new_status', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'DriverStatusAudit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ENTER', 'Enter'), ('EXIT', 'Exit')], max_length=10)),
                ('capturedAt', models.DateTimeField(auto_now_add=True, db_column='capturedAt')),
            ],
            options={
                'db_table': 'GeofenceEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20)),
                ('groupingMethod', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], db_column='groupingMethod', default='AUTOMATIC', max_length=20)),
                ('totalDistanceMeters', models.IntegerField(db_column='totalDistanceMeters', default=0, help_text='Distância acumulada do manifesto.')),
                ('totalEtaSeconds', models.IntegerField(db_column='totalEtaSeconds', default=0, help_text='Tempo estimado total.')),
                ('lockedAt', models.DateTimeField(blank=True, db_column='lockedAt', null=True)),
                ('completedAt', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
            ],
            options={
                'verbose_name': 'Manifesto',
                'verbose_name_plural': 'Manifestos',
                'db_table': 'Manifest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManifestStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'ManifestStop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('READY_FOR_DISPATCH', 'Ready For Dispatch'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('STARTED', 'Started'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('CANCELED_IN_TRANSIT', 'Canceled In Transit'), ('RETURNING_TO_STORE', 'Returning To Store'), ('RETURNED', 'Returned')], default='PREPARING', max_length=30)),
                ('fareValueCents', models.IntegerField(db_column='fareValueCents', help_text='Valor da entrega computado pelas regras financeiras.')),
                ('storeAuthorizedBonusCents', models.IntegerField(db_column='storeAuthorizedBonusCents', default=0)),
                ('distanceMeters', models.IntegerField(db_column='distanceMeters')),
                ('businessDate', models.DateField(db_column='businessDate', help_text='Data de corte fiscal para a fatura.')),
                ('allocationDifficulty', models.BooleanField(db_column='allocationDifficulty', default=False)),
                ('requestedAt', models.DateTimeField(auto_now_add=True, db_column='requestedAt')),
                ('acceptedAt', models.DateTimeField(blank=True, db_column='acceptedAt', null=True)),
                ('startedAt', models.DateTimeField(blank=True, db_column='startedAt', null=True)),
                ('arrivedAt', models.DateTimeField(blank=True, db_column='arrivedAt', null=True)),
                ('completedAt', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
                ('canceledAt', models.DateTimeField(blank=True, db_column='canceledAt', null=True)),
                ('external_order_id', models.CharField(blank=True, db_column='external_order_id', max_length=255, null=True)),
                ('external_source', models.CharField(blank=True, db_column='external_source', help_text="Ex: 'ifood', 'hubster', 'delivery_direto'", max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Payload legado da Machine')),
            ],
            options={
                'verbose_name': 'Pedido de Entrega',
                'verbose_name_plural': 'Pedidos de Entrega',
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAssignmentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'OrderAssignmentAudit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(db_column='postalCode', max_length=15)),
                ('accessCode', models.CharField(blank=True, db_column='accessCode', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'Place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('heading', models.IntegerField()),
                ('speedKmh', models.IntegerField(db_column='speedKmh')),
                ('capturedAt', models.DateTimeField(db_column='capturedAt')),
            ],
            options={
                'db_table': 'Position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyDataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('subjectType', models.CharField(db_column='subjectType', default='DRIVER', max_length=30)),
                ('requestType', models.CharField(db_column='requestType', max_length=30)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolvedAt', models.DateTimeField(blank=True, db_column='resolvedAt', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'PrivacyDataRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('SIGNATURE', 'Signature'), ('SCAN', 'Scan')], default='PHOTO', max_length=20)),
                ('stage', models.CharField(default='DELIVERY', max_length=20)),
                ('fileUrl', models.TextField(db_column='fileUrl', help_text='URI do arquivo físico armazenado.')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('gpsAccuracyMeters', models.IntegerField(blank=True, db_column='gpsAccuracyMeters', null=True)),
                ('deviceIdentifier', models.CharField(blank=True, db_column='deviceIdentifier', max_length=255, null=True)),
                ('confirmationCode', models.CharField(blank=True, db_column='confirmationCode', max_length=100, null=True)),
                ('qrCode', models.CharField(blank=True, db_column='qrCode', max_length=255, null=True)),
                ('barcode', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('capturedAt', models.DateTimeField(auto_now_add=True, db_column='capturedAt')),
            ],
            options={
                'db_table': 'Proof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('date', models.DateField()),
                ('minGuaranteedOverrideCents', models.BigIntegerField(blank=True, db_column='minGuaranteedOverrideCents', null=True)),
            ],
            options={
                'db_table': 'ScheduleEntry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Justificativa obrigatória para a troca de escala.')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'verbose_name': 'Auditoria de Escala',
                'verbose_name_plural': 'Auditorias de Escala',
                'db_table': 'ScheduleEntryAudit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(geography=True, help_text='Polígono delimitador (Geofence).', srid=4326)),
            ],
            options={
                'db_table': 'ServiceZone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('RETURN', 'Return')], default='DROPOFF', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('requiresPin', models.BooleanField(db_column='requiresPin', default=False)),
                ('deliveryPinHash', models.TextField(blank=True, db_column='deliveryPinHash', null=True)),
                ('completedAt', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados do cliente e endereço')),
            ],
            options={
                'db_table': 'Stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(help_text='Identificação única da loja na rede.', max_length=255)),
                ('averagePrepTimeMinutes', models.IntegerField(db_column='averagePrepTimeMinutes', default=15, help_text='Tempo médio de preparo para estimativa do SLA.')),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geolocalização (Lat/Lng) da loja para cálculos ST_DWithin.', srid=4326)),
                ('operational', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'Store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'StoreDriver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.TimeField(db_column='startTime')),
                ('endTime', models.TimeField(db_column='endTime')),
            ],
            options={
                'db_table': 'Turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(help_text='Placa ou identificação visual.', max_length=10, unique=True)),
                ('type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car')], default='MOTORCYCLE', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
    ]
